[[it_aggregate]]
month = "2025-12"
label = "Dezember 2025"
unemployed = 57_186
seeking = 91_596

[[it_aggregate]]
month = "2025-11"
label = "November 2025"
unemployed = 56_909
seeking = 89_416

[[it_aggregate]]
month = "2025-10"
label = "Oktober 2025"
unemployed = 57_375
seeking = 87_941

[[it_aggregate]]
month = "2025-09"
label = "September 2025"
unemployed = 57_665
seeking = 87_556

[[it_aggregate]]
month = "2025-08"
label = "August 2025"
unemployed = 58_288
seeking = 87_684

[[it_aggregate]]
month = "2025-07"
label = "Juli 2025"
unemployed = 57_267
seeking = 86_494

[[it_aggregate]]
month = "2025-06"
label = "Juni 2025"
unemployed = 53_404
seeking = 83_990

[[it_aggregate]]
month = "2025-05"
label = "Mai 2025"
unemployed = 52_373
seeking = 82_174

[[it_aggregate]]
month = "2025-04"
label = "April 2025"
unemployed = 51_865
seeking = 81_599

[[it_aggregate]]
month = "2025-03"
label = "März 2025"
unemployed = 50_973
seeking = 80_580

[[it_aggregate]]
month = "2025-02"
label = "Februar 2025"
unemployed = 50_125
seeking = 79_155

[[it_aggregate]]
month = "2025-01"
label = "Januar 2025"
unemployed = 49_338
seeking = 77_444

[[it_aggregate]]
month = "2024-12"
label = "Dezember 2024"
unemployed = 46_293
seeking = 77_330

[[it_aggregate]]
month = "2024-11"
label = "November 2024"
unemployed = 45_705
seeking = 75_579

[[it_aggregate]]
month = "2024-10"
label = "Oktober 2024"
unemployed = 45_828
seeking = 74_168

[[it_aggregate]]
month = "2024-09"
label = "September 2024"
unemployed = 45_951
seeking = 73_526

[[it_aggregate]]
month = "2024-08"
label = "August 2024"
unemployed = 46_527
seeking = 74_126

[[it_aggregate]]
month = "2024-07"
label = "Juli 2024"
unemployed = 45_042
seeking = 72_913

[[it_aggregate]]
month = "2024-06"
label = "Juni 2024"
unemployed = 42_070
seeking = 70_836

[[it_aggregate]]
month = "2024-05"
label = "Mai 2024"
unemployed = 40_615
seeking = 68_362

[[it_aggregate]]
month = "2024-04"
label = "April 2024"
unemployed = 40_057
seeking = 66_935

[[it_jobs]]
month = "2025-12"
label = "Dezember 2025"
it_jobs = 11_725

[[it_jobs]]
month = "2025-11"
label = "November 2025"
it_jobs = 11_668

[[it_jobs]]
month = "2025-10"
label = "Oktober 2025"
it_jobs = 11_736

[[it_jobs]]
month = "2025-09"
label = "September 2025"
it_jobs = 11_942

[[it_jobs]]
month = "2025-08"
label = "August 2025"
it_jobs = 12_319

[[it_jobs]]
month = "2025-07"
label = "Juli 2025"
it_jobs = 12_279

[[it_jobs]]
month = "2025-06"
label = "Juni 2025"
it_jobs = 12_964

[[it_jobs]]
month = "2025-05"
label = "Mai 2025"
it_jobs = 13_135

[[it_jobs]]
month = "2025-04"
label = "April 2025"
it_jobs = 13_923

[[it_jobs]]
month = "2025-03"
label = "März 2025"
it_jobs = 14_047

[[it_jobs]]
month = "2025-02"
label = "Februar 2025"
it_jobs = 13_908

[[it_jobs]]
month = "2025-01"
label = "Januar 2025"
it_jobs = 13_515

[[it_jobs]]
month = "2024-12"
label = "Dezember 2024"
it_jobs = 14_154

[[it_jobs]]
month = "2024-11"
label = "November 2024"
it_jobs = 14_450

[[it_jobs]]
month = "2024-10"
label = "Oktober 2024"
it_jobs = 14_910

[[it_jobs]]
month = "2024-09"
label = "September 2024"
it_jobs = 15_373

[[it_jobs]]
month = "2024-08"
label = "August 2024"
it_jobs = 16_054

[[it_jobs]]
month = "2024-07"
label = "Juli 2024"
it_jobs = 16_344

[[it_jobs]]
month = "2024-06"
label = "Juni 2024"
it_jobs = 16_491

[[it_jobs]]
month = "2024-05"
label = "Mai 2024"
it_jobs = 16_909

[[it_jobs]]
month = "2024-04"
label = "April 2024"
it_jobs = 17_180

[[germany]]
month = "2025-12"
label = "12/25"
unemployed = 2_907_991
seeking = 4_677_781
jobs = 619_351

[[germany]]
month = "2025-11"
label = "11/25"
unemployed = 2_885_087
seeking = 4_625_403
jobs = 623_934

[[germany]]
month = "2025-10"
label = "10/25"
unemployed = 2_910_752
seeking = 4_616_400
jobs = 623_202

[[germany]]
month = "2025-09"
label = "09/25"
unemployed = 2_954_747
seeking = 4_610_932
jobs = 629_638

[[germany]]
month = "2025-08"
label = "08/25"
unemployed = 3_025_136
seeking = 4_674_742
jobs = 631_058

[[germany]]
month = "2025-07"
label = "07/25"
unemployed = 2_979_486
seeking = 4_643_574
jobs = 628_056

[[germany]]
month = "2024-12"
label = "12/24"
unemployed = 2_806_625
seeking = 4_646_396
jobs = 654_251

[[germany]]
month = "2024-11"
label = "11/24"
unemployed = 2_774_028
seeking = 4_589_481
jobs = 667_713

[[germany]]
month = "2024-10"
label = "10/24"
unemployed = 2_790_529
seeking = 4_572_534
jobs = 688_742

[[germany]]
month = "2024-08"
label = "08/24"
unemployed = 2_871_913
seeking = 4_615_877
jobs = 698_868

[[germany]]
month = "2024-07"
label = "07/24"
unemployed = 2_808_720
seeking = 4_581_507
jobs = 703_119

[[infra_aggregate]]
month = "2025-12"
label = "Dezember 2025"
unemployed = 14_574
seeking = 23_601

[[infra_aggregate]]
month = "2025-11"
label = "November 2025"
unemployed = 14_492
seeking = 22_965

[[infra_aggregate]]
month = "2025-10"
label = "Oktober 2025"
unemployed = 14_485
seeking = 22_365

[[infra_aggregate]]
month = "2025-09"
label = "September 2025"
unemployed = 14_216
seeking = 21_985

[[infra_aggregate]]
month = "2025-08"
label = "August 2025"
unemployed = 14_287
seeking = 21_826

[[infra_aggregate]]
month = "2025-07"
label = "Juli 2025"
unemployed = 14_029
seeking = 21_519

[[infra_aggregate]]
month = "2025-06"
label = "Juni 2025"
unemployed = 13_507
seeking = 21_162

[[infra_aggregate]]
month = "2025-05"
label = "Mai 2025"
unemployed = 13_205
seeking = 20_798

[[infra_aggregate]]
month = "2025-04"
label = "April 2025"
unemployed = 13_047
seeking = 20_663

[[infra_aggregate]]
month = "2025-03"
label = "März 2025"
unemployed = 12_777
seeking = 20_459

[[infra_aggregate]]
month = "2025-02"
label = "Februar 2025"
unemployed = 12_365
seeking = 20_040

[[infra_aggregate]]
month = "2025-01"
label = "Januar 2025"
unemployed = 12_408
seeking = 19_688

[[infra_aggregate]]
month = "2024-12"
label = "Dezember 2024"
unemployed = 11_621
seeking = 19_708

[[infra_aggregate]]
month = "2024-11"
label = "November 2024"
unemployed = 11_490
seeking = 19_333

[[infra_aggregate]]
month = "2024-10"
label = "Oktober 2024"
unemployed = 11_440
seeking = 18_903

[[infra_aggregate]]
month = "2024-09"
label = "September 2024"
unemployed = 11_405
seeking = 18_559

[[infra_aggregate]]
month = "2024-08"
label = "August 2024"
unemployed = 11_381
seeking = 18_599

[[infra_aggregate]]
month = "2024-07"
label = "Juli 2024"
unemployed = 10_930
seeking = 18_162

[[infra_aggregate]]
month = "2024-06"
label = "Juni 2024"
unemployed = 10_537
seeking = 17_786

[[infra_aggregate]]
month = "2024-05"
label = "Mai 2024"
unemployed = 10_251
seeking = 17_322

[[infra_aggregate]]
month = "2024-04"
label = "April 2024"
unemployed = 10_056
seeking = 17_000

[[infra_jobs]]
month = "2025-12"
label = "Dezember 2025"
it_jobs = 2_874

[[infra_jobs]]
month = "2025-11"
label = "November 2026"
it_jobs = 2_740

[[infra_jobs]]
month = "2025-10"
label = "Oktober 2025"
it_jobs = 2_800

[[infra_jobs]]
month = "2025-09"
label = "September 2025"
it_jobs = 2_872

[[infra_jobs]]
month = "2025-08"
label = "August 2025"
it_jobs = 2_941

[[infra_jobs]]
month = "2025-07"
label = "Juli 2025"
it_jobs = 2_948

[[infra_jobs]]
month = "2025-06"
label = "Juni 2025"
it_jobs = 3_199

[[infra_jobs]]
month = "2025-05"
label = "Mai 2025"
it_jobs = 3_272

[[infra_jobs]]
month = "2025-04"
label = "April 2025"
it_jobs = 3_497

[[infra_jobs]]
month = "2025-03"
label = "März 2025"
it_jobs = 3_501

[[infra_jobs]]
month = "2025-02"
label = "Februar 2025"
it_jobs = 3_390

[[infra_jobs]]
month = "2025-01"
label = "Januar 2025"
it_jobs = 3_358

[[infra_jobs]]
month = "2024-12"
label = "Dezember 2024"
it_jobs = 3_430

[[infra_jobs]]
month = "2024-11"
label = "November 2024"
it_jobs = 3_627

[[infra_jobs]]
month = "2024-10"
label = "Oktober 2024"
it_jobs = 3_721

[[infra_jobs]]
month = "2024-09"
label = "September 2024"
it_jobs = 3_815

[[infra_jobs]]
month = "2024-08"
label = "August 2024"
it_jobs = 3_886

[[infra_jobs]]
month = "2024-07"
label = "Juli 2024"
it_jobs = 3_963

[[infra_jobs]]
month = "2024-06"
label = "Juni 2024"
it_jobs = 4_096

[[infra_jobs]]
month = "2024-05"
label = "Mai 2024"
it_jobs = 4_096

[[infra_jobs]]
month = "2024-04"
label = "April 2024"
it_jobs = 4_022

[[software_aggregate]]
month = "2025-12"
label = "Dezember 2025"
unemployed = 18_847
seeking = 30_245

[[software_aggregate]]
month = "2025-11"
label = "November 2025"
unemployed = 18_842
seeking = 29_596

[[software_aggregate]]
month = "2025-10"
label = "Oktober 2025"
unemployed = 19_076
seeking = 29_252

[[software_aggregate]]
month = "2025-09"
label = "September 2025"
unemployed = 19_284
seeking = 29_175

[[software_aggregate]]
month = "2025-08"
label = "August 2025"
unemployed = 19_474
seeking = 29_416

[[software_aggregate]]
month = "2025-07"
label = "Juli 2025"
unemployed = 19_119
seeking = 29_006

[[software_aggregate]]
month = "2025-06"
label = "Juni 2025"
unemployed = 17_690
seeking = 28_078

[[software_aggregate]]
month = "2025-05"
label = "Mai 2025"
unemployed = 17_294
seeking = 27_343

[[software_aggregate]]
month = "2025-04"
label = "April 2025"
unemployed = 17_131
seeking = 27_114

[[software_aggregate]]
month = "2025-03"
label = "März 2025"
unemployed = 16_828
seeking = 26_732

[[software_aggregate]]
month = "2025-02"
label = "Februar 2025"
unemployed = 16_564
seeking = 26_187

[[software_aggregate]]
month = "2025-01"
label = "Januar 2025"
unemployed = 16_184
seeking = 25_597

[[software_aggregate]]
month = "2024-12"
label = "Dezember 2024"
unemployed = 15_188
seeking = 25_465

[[software_aggregate]]
month = "2024-11"
label = "November 2024"
unemployed = 14_798
seeking = 24_628

[[software_aggregate]]
month = "2024-10"
label = "Oktober 2024"
unemployed = 14_931
seeking = 24_183

[[software_aggregate]]
month = "2024-09"
label = "September 2024"
unemployed = 15_019
seeking = 24_108

[[software_aggregate]]
month = "2024-08"
label = "August 2024"
unemployed = 15_147
seeking = 24_262

[[software_aggregate]]
month = "2024-07"
label = "Juli 2024"
unemployed = 14_565
seeking = 23_780

[[software_aggregate]]
month = "2024-06"
label = "Juni 2024"
unemployed = 13_428
seeking = 22_953

[[software_aggregate]]
month = "2024-05"
label = "Mai 2024"
unemployed = 12_884
seeking = 21_896

[[software_aggregate]]
month = "2024-04"
label = "April 2024"
unemployed = 12_534
seeking = 21_414

[[software_jobs]]
month = "2025-12"
label = "Dezember 2025"
it_jobs = 1_849

[[software_jobs]]
month = "2025-11"
label = "November 2025"
it_jobs = 1_856

[[software_jobs]]
month = "2025-10"
label = "Oktober 2025"
it_jobs = 1_859

[[software_jobs]]
month = "2025-09"
label = "September 2025"
it_jobs = 1_902

[[software_jobs]]
month = "2025-08"
label = "August 2025"
it_jobs = 2_014

[[software_jobs]]
month = "2025-07"
label = "Juli 2025"
it_jobs = 2_016

[[software_jobs]]
month = "2025-06"
label = "Juni 2025"
it_jobs = 2_113

[[software_jobs]]
month = "2025-05"
label = "Mai 2025"
it_jobs = 2_147

[[software_jobs]]
month = "2025-04"
label = "April 2025"
it_jobs = 2_147

[[software_jobs]]
month = "2025-03"
label = "März 2025"
it_jobs = 2_277

[[software_jobs]]
month = "2025-02"
label = "Februar 2025"
it_jobs = 2_283

[[software_jobs]]
month = "2025-01"
label = "Januar 2025"
it_jobs = 2_268

[[software_jobs]]
month = "2024-12"
label = "Dezember 2024"
it_jobs = 2_379

[[software_jobs]]
month = "2024-11"
label = "November 2024"
it_jobs = 2_385

[[software_jobs]]
month = "2024-10"
label = "Oktober 2024"
it_jobs = 2_481

[[software_jobs]]
month = "2024-09"
label = "September 2024"
it_jobs = 2_563

[[software_jobs]]
month = "2024-08"
label = "August 2024"
it_jobs = 2_680

[[software_jobs]]
month = "2024-07"
label = "Juli 2024"
it_jobs = 2_774

[[software_jobs]]
month = "2024-06"
label = "Juni 2024"
it_jobs = 2_891

[[software_jobs]]
month = "2024-05"
label = "Mai 2024"
it_jobs = 2_891

[[software_jobs]]
month = "2024-04"
label = "April 2024"
it_jobs = 2_959
